apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: plapp
  template:
    metadata:
      labels:
        app: plapp
    spec:
      containers:
      - name: plapp
        image: icr.io/plapp/plasma@sha256:b2c47beaea88fc0248acc525df80b4e8ac139c7f46e2bac4ad50fcd73b7e8c53
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: plapp
  type: NodePort
  ports:
   - port: 5000
     nodePort: 31514